# Generated by Django 3.2.9 on 2021-12-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contactformsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormSubmission',
        ),
    ]
