# Generated by Django 3.2.9 on 2021-12-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contactrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
    ]
