# Generated by Django 3.2.9 on 2021-12-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
