# Generated by Django 3.2.9 on 2021-12-09 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211208_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 9, 11, 5, 38, 441805)),
        ),
    ]
