# Generated by Django 3.2.9 on 2021-12-09 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_category_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 9, 11, 10, 20, 855692)),
        ),
    ]
